version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_agro
    environment:
      POSTGRES_DB: agrodb
      POSTGRES_USER: agro
      POSTGRES_PASSWORD: agro123
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: sistema_agro
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agrodb
      SPRING_DATASOURCE_USERNAME: agro
      SPRING_DATASOURCE_PASSWORD: agro123
    depends_on:
      - postgres